maps/cs_oldmansion.bsp
maps/cs_oldmansion.txt
sound/mansion/attic.wav
sound/mansion/clock_bell.wav
sound/mansion/clock_tick.wav
sound/mansion/crows.wav
sound/mansion/mistery1.wav
sound/mansion/mistery2.wav
sound/mansion/mistery3.wav
sound/mansion/mistery4.wav
sound/mansion/piano.wav
sound/mansion/scream.wav
sound/mansion/thunder.wav
sound/mansion/wind.wav
sound/mansion/wolves1.wav
sound/mansion/wolves2.wav
sprites/skull.spr
overviews/cs_oldmansion.bmp
overviews/cs_oldmansion.txt
