overviews/cscz_winterassault.bmp
overviews/cscz_winterassault.txt
gfx/env/perisbk.tga
gfx/env/perisdn.tga
gfx/env/perisft.tga
gfx/env/perislf.tga
gfx/env/perisrt.tga
gfx/env/perisup.tga
halflife.wad
models/cs_winterassault_cz/3dm_sofa.mdl
models/cs_winterassault_cz/3dm_tafel.mdl
models/cs_winterassault_cz/briefcase_money.mdl
models/cs_winterassault_cz/cam.mdl
models/cs_winterassault_cz/laptop.mdl
models/cs_winterassault_cz/leiche_sitz.mdl
models/cs_winterassault_cz/paper_stack.mdl
models/cs_winterassault_cz/roofstuff01.mdl
models/cs_winterassault_cz/streetlamp01.mdl
models/cs_winterassault_cz/tank_body.mdl
models/cs_winterassault_cz/tank_cannon.mdl
models/cs_winterassault_cz/tank_turret.mdl
models/cs_winterassault_cz/tree01.mdl
models/dod_tree1.mdl
models/hostage.mdl
models/props/ac_large.mdl
models/props/stepvan.mdl
models/props/tree_noleaves.mdl
models/props/tree_noleaves2.mdl
models/props/tree_pine.mdl
models/props/truck_large-brown.mdl
models/props/truck_russian-large.mdl
models/xen_tree1.mdl
sound/ambience/industrial4.wav
sound/ambience/wind2.wav
sound/cs_winterassault_cz/gue_ak47.wav
sound/cs_winterassault_cz/gue_mgun.wav
sound/cs_winterassault_cz/gue_mortar2.wav
sound/cs_winterassault_cz/gue_tankidle1.wav
sprites/3dm_leaves4.spr
sprites/b-tele1.spr
sprites/flare1.spr
sprites/glow04.spr
sprites/lgtning.spr
