gfx/env/mad_snow3_bk.tga
gfx/env/mad_snow3_dn.tga
gfx/env/mad_snow3_ft.tga
gfx/env/mad_snow3_lf.tga.tga
gfx/env/mad_snow3_rt.tga.tga
gfx/env/mad_snow3_up.tga.tga
models/de_alps/mad_sgrass1.mdl
models/de_alps/mad_tree1.mdl
models/de_alps/mad_tree2.mdl
models/de_alps/mad_tree3.mdl
models/de_alps/mad_tree4.mdl
sprites/de_alps/colflare.spr
sprites/de_alps/rauchsprite1.spr
sound/de_alps/all_ambience1.wav
sound/de_alps/all_bell.wav
sound/de_alps/all_bird1.wav
sound/de_alps/all_bird2.wav
sound/de_alps/all_cat1.wav
sound/de_alps/all_crow1.wav
sound/de_alps/all_crow2.wav
sound/de_alps/all_wind1.wav
sound/de_alps/all_wind2.wav
sound/de_alps/all_wolf1.wav
sound/de_alps/lo_cave1.wav
sound/de_alps/lo_cavedrips.wav
sound/de_alps/lo_chimes.wav
sound/de_alps/lo_organ_loop.wav
sound/de_alps/lo_water1.wav
overviews/de_alps.bmp
overviews/de_alps.txt
maps/de_alps.bsp
maps/de_alps.txt
maps/de_alps_readme.txt
maps/de_alps.res
de_alps.wad

