//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_chernobyl
//
// Download @: http://dwl.17buddies.net/link/map/11107/de_chernobyl.html
//
//////////////////////////////////////////////////////////
gfx/env/pasmurnoup.tga
gfx/env/pasmurnodn.tga
gfx/env/pasmurnolf.tga
gfx/env/pasmurnort.tga
gfx/env/pasmurnoft.tga
gfx/env/pasmurnobk.tga

models/player/leet/leet.mdl
models/player/gsg9/gsg9.mdl 
models/chernobyl/bookcase_arched.mdl
models/chernobyl/bookcase_brown-wood.mdl
models/chernobyl/bookcase_fancy-wood.mdl
models/chernobyl/budka_kalash.mdl 
models/chernobyl/bush_evergreen.mdl
models/chernobyl/bush_noleaves.mdl
models/chernobyl/couch_fabric-wreck.mdl
models/chernobyl/dod_tree1.mdl
models/chernobyl/flo_grass.mdl
models/chernobyl/flo_grass2.mdl
models/chernobyl/furgon_kalash.mdl
models/chernobyl/furniture.mdl
models/chernobyl/grasD.mdl
models/chernobyl/grasE.mdl
models/chernobyl/grasF.mdl
models/chernobyl/hos_bench.mdl
models/chernobyl/kotushka_kalash.mdl
models/chernobyl/lag_oaktree.mdl
models/chernobyl/lampa.mdl
models/chernobyl/lip_cabinet_dark.mdl
models/chernobyl/lip_dresser.mdl
models/chernobyl/map.mdl
models/chernobyl/mattress_wreck.mdl
models/chernobyl/pine_tree.mdl
models/chernobyl/pipe_double.mdl
models/chernobyl/Rama.mdl
models/chernobyl/rubble_set.mdl
models/chernobyl/stolb_2.mdl
models/chernobyl/table_sofa-wreck.mdl
models/chernobyl/topol1.mdl
models/chernobyl/train_coupler.mdl 
models/chernobyl/train_wheels.mdl
models/chernobyl/tree_noleaves.mdl
models/chernobyl/tree_noleavesv01.mdl
models/chernobyl/tree_noleavesv2.mdl 
models/chernobyl/tree_pine.mdl 
models/chernobyl/washingmachine.mdl
 
sound/chernobyl/boomer.wav
sound/chernobyl/crow.wav
sound/chernobyl/dog.wav
sound/chernobyl/drips.wav
sound/chernobyl/geiger.wav
sound/chernobyl/wind.wav
sound/chernobyl/wolf.wav
 
overviews/de_chernobyl.txt
overviews/de_chernobyl.bmp
