gfx/env/de_docklandup.tga
gfx/env/de_docklanddn.tga
gfx/env/de_docklandlf.tga
gfx/env/de_docklandrt.tga
gfx/env/de_docklandft.tga
gfx/env/de_docklandbk.tga
models/de_dockland/bulb1.mdl
models/de_dockland/xen_trailer.mdl
models/de_dockland/SAS.mdl
models/de_dockland/gins_shelvesA.mdl
models/de_dockland/tree.mdl
models/de_dockland/bite.mdl
models/de_dockland/grille.mdl
models/de_dockland/bureau.mdl
sound/de_dockland/porte.wav
sprites/glow01.spr
sound/de_dockland/helico.wav
sound/de_dockland/claxon.wav
sound/de_dockland/mer.wav
sound/de_dockland/ventilo.wav
sound/de_dockland/intro.wav
sound/de_dockland/egout.wav
models/de_dockland/Echelle.mdl
models/de_dockland/tanker.mdl
models/de_dockland/poteau.mdl
models/de_dockland/barriere.mdl
models/de_dockland/car.mdl
overviews/de_dockland.txt
overviews/de_dockland.tga
maps/de_dockland.res
