// de_kievpass.res
// .res entries (42):

gfx/env/kievpassup.tga
gfx/env/kievpassdn.tga
gfx/env/kievpasslf.tga
gfx/env/kievpassrt.tga
gfx/env/kievpassft.tga
gfx/env/kievpassbk.tga
models/de_kievpass/lamp1.mdl
models/de_kievpass/lamp2.mdl
models/de_kievpass/lamp3.mdl
models/de_kievpass/lamp4.mdl
models/de_kievpass/lavka1.mdl
models/de_kievpass/lustra1.mdl
models/de_kievpass/eskalator.mdl
models/de_kievpass/peron_top.mdl
models/de_kievpass/ograda1.mdl
models/de_kievpass/lavka2.mdl
models/de_kievpass/infopost.mdl
models/de_kievpass/reklama1.mdl
models/de_kievpass/arrival1.mdl
models/de_kievpass/fern.mdl
models/de_kievpass/bobik.mdl
models/de_kievpass/ograda2.mdl
models/de_kievpass/lamp5.mdl
models/de_kievpass/ograda3.mdl
models/de_kievpass/vcon.mdl
models/de_kievpass/peron_bot.mdl
models/de_kievpass/ograda4.mdl
models/de_kievpass/butka_gls.mdl
models/de_kievpass/butka.mdl
models/de_kievpass/phone.mdl
models/de_kievpass/tv.mdl
models/de_kievpass/mconcr.mdl
models/de_kievpass/lamp6.mdl
models/de_kievpass/reklama2.mdl
sound/de_kievpass/kp_cnct.wav
sound/de_kievpass/kp_par.wav
sound/de_kievpass/kp_esk.wav
sound/de_kievpass/kp_fon.wav
sound/de_kievpass/kp_engn.wav
sound/de_kievpass/kp_tak.wav
overviews/de_kievpass.bmp
overviews/de_kievpass.txt
