maps/de_kabul.res
maps/de_kabul.txt
sound/misc/headshot.wav
sound/misc/prepare.wav
sound/misc/dominating.wav
sound/misc/doublekill.wav
sound/misc/firstblood.wav
sound/misc/godlike.wav
sound/misc/humiliation.wav
sound/misc/monsterkill.wav
sound/misc/multikill.wav
sound/misc/rampage.wav
sound/misc/ultrakill.wav
sound/misc/unstoppable.wav
sound/misc/oneandonly.wav 
sound/misc/killingspree.wav
