gfx/env/mhup.tga
gfx/env/mhdn.tga
gfx/env/mhlf.tga
gfx/env/mhrt.tga
gfx/env/mhft.tga
gfx/env/mhbk.tga
sound/ambience/mountainhamlet/erriewind_mw.wav
sound/ambience/mountainhamlet/scream.wav
sound/ambience/mountainhamlet/waterrun_mw.wav
sound/ambience/mountainhamlet/falls_mw.wav
sound/ambience/mountainhamlet/chickamb.wav
sound/ambience/mountainhamlet/chinamusic.wav
sound/ambience/mountainhamlet/woodcreak.wav
sound/ambience/mountainhamlet/towerbell.wav
sound/ambience/mountainhamlet/toad.wav
sound/ambience/mountainhamlet/birds.wav
sound/ambience/mountainhamlet/bubble_mw.wav
sound/ambience/mountainhamlet/sink.wav
sound/ambience/mountainhamlet/flush.wav
sound/ambience/mountainhamlet/belltoll_mw.wav
sound/ambience/mountainhamlet/greg_mw.wav
sound/ambience/mountainhamlet/lv_fruit1.wav
sound/ambience/mountainhamlet/killchicken.wav
sound/ambience/mountainhamlet/chkn_alrmd.wav
models/mountainhamlet/palma.mdl
models/mountainhamlet/chamagne.mdl
models/mountainhamlet/grrenbott.mdl
models/mountainhamlet/gunrack1.mdl
models/mountainhamlet/ksp.mdl
models/mountainhamlet/ak5scope.mdl
models/mountainhamlet/lamp_glass.mdl
models/mountainhamlet/chick.mdl
models/mountainhamlet/feather.mdl
models/mountainhamlet/bell.mdl
