maps/de_mantiqueira.bsp
maps/de_mantiqueira.res
maps/de_mantiqueira.txt
maps/de_mantiqueira.nav
gfx/env/sdmantiqueirabk.tga
gfx/env/sdmantiqueiradn.tga
gfx/env/sdmantiqueiraft.tga
gfx/env/sdmantiqueiralf.tga
gfx/env/sdmantiqueirart.tga
gfx/env/sdmantiqueiraup.tga
models/Spock_mantiqueira/arvore001.mdl
models/Spock_mantiqueira/pinheiro.mdl
models/Spock_mantiqueira/arvore003.mdl
sound/Spock_mantiqueira/busao.wav
sound/Spock_mantiqueira/vento.wav
models/Spock_mantiqueira/brilho1.spr
models/Spock_mantiqueira/luz.mdl
models/Spock_mantiqueira/garrafas.mdl
models/Spock_mantiqueira/geladeiras.mdl
sound/Spock_mantiqueira/intro.wav
models/Spock_mantiqueira/silverado.mdl
sound/Spock_mantiqueira/balada2.wav
sound/Spock_mantiqueira/balada1.wav
models/spock_mantiqueira/busao.mdl
models/Spock_mantiqueira/poste.mdl
sound/Spock_mantiqueira/portao1.wav
sound/Spock_mantiqueira/porta1.wav
models/Spock_mantiqueira/fumaca2.spr
models/Spock_mantiqueira/explo1.spr
models/Spock_mantiqueira/explo2.spr
models/Spock_mantiqueira/arvore.mdl
overviews/de_mantiqueira.bmp
overviews/de_mantiqueira.txt

