maps/de_nuke_rota.res
maps/de_nuke_rota.txt
maps/de_nuke_rota.nav
gfx/env/morningdewbk.tga
gfx/env/morningdewft.tga
gfx/env/morningdewrt.tga
gfx/env/morningdewdn.tga
gfx/env/morningdewlf.tga
gfx/env/morningdewup.tga
overviews/de_nuke_rota.bmp
overviews/de_nuke_rota.txt
sound/ambience/cricket.wav
sound/ambience/camp_water.wav
sound/ambience/forest_amb5.wav
sound/ambience/computalk1.wav
sound/ambience/computalk2.wav
sound/ambience/cricket.wav
sound/ambience/drips.wav
sound/ambience/industrial2.wav
sound/ambience/truck1.wav
models/props/barrels_biohazard.mdl
models/props/barrelcrash.mdl
models/props/bush1.mdl
models/props/chair_office-leather.mdl
models/props/couch_green.mdl
models/props/deskc_ritual.mdl
models/props/deskl_ritual.mdl
models/props/deskm_ritual.mdl
models/props/desks_ritual.mdl
models/props/dumpster_lidclosed.mdl
models/props/filecabinet_4dr-group2.mdl
models/props/flag_us.mdl
models/props/lamp_citylight_small.mdl
models/props/lamp_hanging-industrial.mdl
models/props/PC.mdl
models/props/pc1.mdl
models/props/pc2.mdl
models/props/pc3.mdl
models/props/rota_industrial.mdl
models/props/rota_terrorist_truck.mdl
models/props/superbomb2.mdl
models/props/tree_gshaded.mdl
models/props/wlight2.mdl
models/cs_greatassault/cam.mdl
sprites/glow01.spr
sprites/xsmoke1.spr

