de_promzone.wad
gfx/env/trainyardup.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardft.tga
gfx/env/trainyardbk.tga
sound/ambience/boomer.wav
sound/ambience/voltage.wav
sprites/fire.spr
sprites/glow01.spr
sound/ambience/lv_neon.wav
sprites/p_trava.spr
models/p_provod2.mdl
models/p_provod3.mdl
models/p_provod1.mdl
models/p_provod4.mdl
models/p_kamen1.mdl
models/p_provod_sh.mdl
