gfx/env/kitchoonup.tga
gfx/env/kitchoondn.tga
gfx/env/kitchoonlf.tga
gfx/env/kitchoonrt.tga
gfx/env/kitchoonft.tga
gfx/env/kitchoonbk.tga
sprites/kitchoon/buzzer_shar.spr
sprites/kitchoon/smokepuff.spr
sprites/kitchoon/teletransp.spr
sound/ambience/kitchoon/aspirateur.wav
sound/ambience/kitchoon/clock-tic.wav
sound/ambience/kitchoon/dog1.wav
sound/ambience/kitchoon/kitch2.wav
sound/ambience/kitchoon/prout.wav
sound/ambience/kitchoon/biere.wav
sound/ambience/kitchoon/comp2.wav
sound/ambience/kitchoon/dog2.wav
sound/ambience/kitchoon/lv_neon.wav
sound/ambience/kitchoon/teletransporteur.wav
sound/ambience/kitchoon/car1.wav
sound/ambience/kitchoon/comp3.wav
sound/ambience/kitchoon/oups.wav
sound/ambience/kitchoon/cat1.wav
sound/ambience/kitchoon/coucou.wav
sound/ambience/kitchoon/joelamouk.wav
sound/ambience/kitchoon/pate.wav
overviews/de_rats_kitchoon.bmp
overviews/de_rats_kitchoon.txt
maps/de_rats_kitchoon.txt
maps/de_rats_kitchoon.bsp
maps/de_rats_kitchoon.res